%%%Inference
JOB_TO_EVAL=yt8m_train_frame_level_rgb_audio_logistic_model
JOB_NAME=yt8m_inference_frame_rgb_audio_logistic_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.inference --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --input_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/test/test*.tfrecord' --train_dir=$BUCKET_NAME/${JOB_TO_EVAL} --model=FrameLevelLogisticModel --run_once=True --frame_features=True --feature_names="rgb, audio" --feature_sizes="1024, 128" --output_file=$BUCKET_NAME/${JOB_TO_EVAL}/predictions.csv --batch_size=256

JOB_TO_EVAL=yt8m_train_frame_level_rgb_audio_dbof_model
JOB_NAME=yt8m_inference_frame_rgb_audio_dbof_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.inference --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --input_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/test/test*.tfrecord' --train_dir=$BUCKET_NAME/${JOB_TO_EVAL} --model=DBoFModel --run_once=True --frame_features=True --feature_names="rgb, audio" --feature_sizes="1024, 128" --output_file=$BUCKET_NAME/${JOB_TO_EVAL}/predictions.csv --batch_size=

JOB_TO_EVAL=yt8m_train_frame_level_rgb_audio_lstm_model
JOB_NAME=yt8m_inference_frame_rgb_lstm_neural_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.inference --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --input_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/validate/validater_.tfrecord' --train_dir=$BUCKET_NAME/${JOB_TO_EVAL} --model=LstmModel --run_once=True --frame_features=True --feature_names="rgb, audio" --feature_sizes="1024, 128" --output_file=$BUCKET_NAME/${JOB_TO_EVAL}/predictions_val.csv --batch_size=128

JOB_TO_EVAL=yt8m_train_frame_level_rgb_audio_neural_model
JOB_NAME=yt8m_inference_frame_rgb_audio_neural_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.inference --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --input_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/test/test*.tfrecord' --train_dir=$BUCKET_NAME/${JOB_TO_EVAL} --model=NeuralNetworkModel --run_once=True --frame_features=True --feature_names="rgb, audio" --feature_sizes="1024, 128" --output_file=$BUCKET_NAME/${JOB_TO_EVAL}/predictions.csv --batch_size=256

JOB_TO_EVAL=yt8m_train_frame_level_rgb_audio_lstm_model
JOB_NAME=yt8m_inference_frame_rgb_audio_lstm_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.inference --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --input_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/test/test*.tfrecord' --train_dir=$BUCKET_NAME/${JOB_TO_EVAL} --model=LstmModel --run_once=True --frame_features=True --feature_names="rgb, audio" --feature_sizes="1024, 128" --output_file=$BUCKET_NAME/${JOB_TO_EVAL}/predictions.csv --batch_size=256

JOB_TO_EVAL=yt8m_train_video_level_logistic_model
JOB_NAME=yt8m_inference_video_logistic_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.inference --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --input_data_pattern='gs://youtube8m-ml-us-east1/1/video_level/test/test*.tfrecord' --train_dir=$BUCKET_NAME/${JOB_TO_EVAL} --model=LogisticModel --run_once=True --output_file=$BUCKET_NAME/${JOB_TO_EVAL}/predictions.csv