%%% NeuralNetworkModel
JOB_NAME=yt8m_train_neural_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.train --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --train_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/train/train*.tfrecord' --model=NeuralNetworkModel --train_dir=$BUCKET_NAME/yt8m_train_frame_level_rgb_neural_model --frame_features=True --feature_names="rgb" --feature_sizes="1024" --start_new_model --batch_size=256 --base_learning_rate=0.001 --learning_rate_decay_examples=5000 --optimizer="GradientDescentOptimizer"

%%% Logistic Regression
JOB_NAME=yt8m_train_logistic_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.train --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --train_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/train/train*.tfrecord' --model=FrameLevelLogisticModel --train_dir=$BUCKET_NAME/yt8m_train_frame_level_rgb_logistic_model --frame_features=True --feature_names="rgb" --feature_sizes="1024" --start_new_model --batch_size=256 --base_learning_rate=0.001 --learning_rate_decay_examples=5000 --optimizer="GradientDescentOptimizer"

%%% DBoFModel
JOB_NAME=yt8m_train_frame_level_rgb_audio_dbof_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.train --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --train_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/train/train*.tfrecord' --model=DBoFModel --train_dir=$BUCKET_NAME/yt8m_train_frame_level_rgb_audio_dbof_model --frame_features=True --feature_names="rgb, audio" --feature_sizes="1024, 128" --batch_size=1024 --base_learning_rate=0.01 --learning_rate_decay_examples=50000 --optimizer="AdamOptimizer"

%%% LSTM
JOB_NAME=yt8m_train_frame_level_rgb_audio_lstm_$(date +%Y%m%d_%H%M%S); gcloud --verbosity=debug ml-engine jobs submit training $JOB_NAME --package-path=youtube-8m --module-name=youtube-8m.train --staging-bucket=$BUCKET_NAME --region=us-east1 --config=youtube-8m/cloudml-gpu.yaml -- --train_data_pattern='gs://youtube8m-ml-us-east1/1/frame_level/train/train*.tfrecord' --model=LstmModel --train_dir=$BUCKET_NAME/yt8m_train_frame_level_rgb_audio_lstm_model --frame_features=True --feature_names="rgb, audio" --feature_sizes="1024, 128" --batch_size=128 --base_learning_rate=0.01 --learning_rate_decay_examples=50000 --optimizer="AdamOptimizer"